# Mandatory settings

remote_theme : poole/hyde

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://vplayv.github.io
baseurl:          /

author:
  name:           'vplayv'
  url:            https://www.linkedin.com/in/yeonggeunyoo/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vplayv/vplayv.github.io
